version: '3'

services:
  token:
    build:
      context: ./token
    restart: "no"
    env_file:
      - ./.env
      - ./token/.${NODE_ENV}.env
    networks:
      - backend
    volumes:
      - ./token/:/var/www/token
      - /var/www/token/node_modules
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
      - rabbitmq
